[project]
name = "JDFTxFreeNrg"
dynamic = ["version"]
requires-python = ">=3.10"
authors = [{ name = "Ben Rich", email = "benjamin.rich@colorado.edu" }]


#TODO: Figure out what version we want for ipykernel
dependencies = [
    "numpy>=1.25.0,<3",
    "ase>=3.23.0",
    "pymatgen@git+https://github.com/benrich37/pymatgen.git",
    "ipykernel",
]

[project.optional-dependencies]
pyvolgrid = ["pyvolgrid"]
qrotor = ["qrotor"]

#[tool.ruff]
#target-version = "py310"
#line-length = 120
#output-format = "concise"

#[tool.pdm.dev-dependencies]
#lint = ["mypy>=1.10.0", "pre-commit>=3.7.1", "ruff>=0.4.9"]

#[tool.pyright]
#typeCheckingMode = "off"
#reportPossiblyUnboundVariable = true
#reportUnboundVariable = true
#reportMissingImports = false
#reportMissingModuleSource = false
#reportInvalidTypeForm = false
#exclude = ["**/tests", "**/examples"]

#[tool.pydocstyle]
#exclude = ["**/tests"]

#[tool.ruff.format]
#docstring-code-format = true